# Generated by Django 6.0.5 on 2026-06-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostmodel',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
