# Generated by Django 6.0.5 on 2026-06-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortal', '0002_jobpostmodel_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='applyjobmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewing', 'Reviewing'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofilemodel',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Recruiter', 'Recruiter'), ('Seeker', 'Seeker')], max_length=100, null=True),
        ),
    ]
